### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by nevinhappy** [leibnitz27/cfr#15]
CFR version: cfr-0.145.jar

Failed call stack :
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.HashMap.resize(HashMap.java:704)
	at java.util.HashMap.putVal(HashMap.java:629)
	at java.util.HashMap.put(HashMap.java:612)
	at org.benf.cfr.reader.bytecode.analysis.opgraph.Op02WithProcessedDataAndRefs.mapSSASlots(Op02WithProcessedDataAndRefs.java:2009)
	at org.benf.cfr.reader.bytecode.analysis.opgraph.Op02WithProcessedDataAndRefs.discoverStorageLiveness(Op02WithProcessedDataAndRefs.java:1996)
	at org.benf.cfr.reader.bytecode.CodeAnalyser.getAnalysisInner(CodeAnalyser.java:334)
	at org.benf.cfr.reader.bytecode.CodeAnalyser.getAnalysisOrWrapFail(CodeAnalyser.java:184)
	at org.benf.cfr.reader.bytecode.CodeAnalyser.getAnalysis(CodeAnalyser.java:122)
	at org.benf.cfr.reader.entities.attributes.AttributeCode.analyse(AttributeCode.java:96)
	at org.benf.cfr.reader.entities.Method.analyse(Method.java:397)
	at org.benf.cfr.reader.entities.ClassFile.analyseMid(ClassFile.java:906)
	at org.benf.cfr.reader.entities.ClassFile.analyseInnerClassesPass1(ClassFile.java:778)
	at org.benf.cfr.reader.entities.ClassFile.analyseMid(ClassFile.java:886)
	at org.benf.cfr.reader.entities.ClassFile.analyseInnerClassesPass1(ClassFile.java:778)
	at org.benf.cfr.reader.entities.ClassFile.analyseMid(ClassFile.java:886)
	at org.benf.cfr.reader.entities.ClassFile.analyseTop(ClassFile.java:797)
	at org.benf.cfr.reader.Driver.doJarVersionTypes(Driver.java:225)
	at org.benf.cfr.reader.Driver.doJar(Driver.java:109)
	at org.benf.cfr.reader.CfrDriverImpl.analyse(CfrDriverImpl.java:65)
	at org.benf.cfr.reader.Main.main(Main.java:48)

**Comment by nevinhappy** [comment]
I was supposed to provide class file to help , but I tried several times, it failed at different class and I monitored the memory , it keep growing high. 
although I solve it by setting large memory for my virtual machine. But the memory leak should be there .

**Comment by leibnitz27** [comment]
It's an out of memory error - so without an input file (please don't upload if you don't have rights on it), I can't really get much out of that.

Things you can try -

* give your JVM more memory
 -Xmx32gb

* try "--lomem true"

* if you're decompiling a jar, unzip it, and just decompile the offending classfile.

If you *can* provide the class, that would be helpful, but again, not if it's proprietary.

**Comment by leibnitz27** [comment]
ping @nevinhappy  - are you able to provide an example to trigger this?

**Comment by leibnitz27** [comment]
Closing this, as it doesn't add value in current state and has been abandoned. Feel free to reopen if you have additional info.
