### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by GraxCode** [leibnitz27/cfr#170]
# CFR version
329eadca515e0f7939f40c3f2355c273548740ef

# Description
Infinite loop: 
```
java.lang.StackOverflowError
	at java.util.HashMap.hash(HashMap.java:338)
	at java.util.HashMap.get(HashMap.java:556)
	at org.benf.cfr.reader.util.collections.LazyMap.get(LazyMap.java:40)
	at org.benf.cfr.reader.util.collections.LazyExceptionRetainingMap.get(LazyExceptionRetainingMap.java:19)
	at org.benf.cfr.reader.state.DCCommonState.getClassFile(DCCommonState.java:179)
	at org.benf.cfr.reader.state.DCCommonState.getClassFile(DCCommonState.java:194)
	at org.benf.cfr.reader.bytecode.analysis.types.JavaRefTypeInstance.getClassFile(JavaRefTypeInstance.java:514)
	at org.benf.cfr.reader.entities.ClassFile.hasAccessibleField(ClassFile.java:522)
	at org.benf.cfr.reader.entities.ClassFile.hasAccessibleField(ClassFile.java:524)
	at org.benf.cfr.reader.entities.ClassFile.hasAccessibleField(ClassFile.java:524)
	at org.benf.cfr.reader.entities.ClassFile.hasAccessibleField(ClassFile.java:524)
	at org.benf.cfr.reader.entities.ClassFile.hasAccessibleField(ClassFile.java:524)
```

# Example
Cannot provide a sample, sorry.

**Comment by GraxCode** [comment]
I think this has something to do with innerclass attributes. Probably when the class is the innerclass itself

**Comment by Marcono1234** [comment]
Could you please replace "latest commit" with the actual commit hash where you reproduced this? While it may be obvious now what the latest commit is, finding that out in a few weeks involves some extra work.

**Comment by GraxCode** [comment]
I was pretty sure @leibnitz27 will fix this asap as this crashes the whole decompiler, not only the class. But I can replace it ofc.

**Comment by GraxCode** [comment]
Closing this as it was my faulty API usage.

**Comment by Toshimichi0915** [comment]
Note: putting a different class name in ClassFileSource#getClassFileContent will result in this behavior.

```java
        @Override
        public Pair<byte[], String> getClassFileContent(String s) throws IOException {
//          if (!s.equals(className)) {
//              throw new FileNotFoundException("Class name mismatch: " + s + " != " + className);
//          }
            return new Pair<>(classFile, "target");
//                                       ^^^^^^^^ <- ERROR!
        }
```
