### ISSUE TITLE
StackOverflowError when decompiling in parallel

### ISSUE THREAD

**Issue by skyrising** [leibnitz27/cfr#250]
# CFR version
0.151

# Compiler
In this example: Javac 6 (Decompiling CFR itself), but should be unrelated to the issue

# Description
When decompiling multiple JARs in parallel CFR can run into an infinite recursion issue while rewriting L-values.
Snippet of the `StackOverflowError`:
```java
	at org.benf.cfr.reader.bytecode.analysis.parse.utils.LValueRewriter$Util.rewriteArgArray(LValueRewriter.java:30)
	at org.benf.cfr.reader.bytecode.analysis.parse.expression.StaticFunctionInvokation.replaceSingleUsageLValues(StaticFunctionInvokation.java:83)
	at org.benf.cfr.reader.bytecode.analysis.parse.utils.LValueAssignmentAndAliasCondenser.getLValueReplacement(LValueAssignmentAndAliasCondenser.java:272)
	at org.benf.cfr.reader.bytecode.analysis.parse.expression.StackValue.replaceSingleUsageLValues(StackValue.java:61)
	at org.benf.cfr.reader.bytecode.analysis.parse.expression.CastExpression.replaceSingleUsageLValues(CastExpression.java:122)
	at org.benf.cfr.reader.bytecode.analysis.parse.utils.LValueRewriter$Util.rewriteArgArray(LValueRewriter.java:30)
```

My suspicion is that this is a race condition on some shared state that shouldn't be shared.

# Example
Here is an example, decompiling CFR itself, that should trigger the bug.
You might need to adjust the loop bound or run it multiple times to get the race condition. On my system 8 is enough and I've also had it happen with only 2 threads when using a bigger JAR.
```java
import org.benf.cfr.reader.api.CfrDriver;

import java.io.File;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

public class CfrStackOverflowTest {
    public static void main(String[] args) throws URISyntaxException {
        String fileName = getTestJar();
        System.out.println(fileName);
        for (int i = 0; i < 8; i++) {
            spawnThread(i, fileName);
        }
    }

	// Find the CFR jar that's on the class path
    private static String getTestJar() throws URISyntaxException {
        URI jarURI = CfrDriver.class.getResource("/org/benf/cfr/reader/api/CfrDriver.class").toURI();
        String fileName = jarURI.getSchemeSpecificPart();
        return fileName.substring(5, fileName.lastIndexOf('!'));
    }

    private static void spawnThread(int id, String jarFile) {
        File outputDir = new File("output-" + id);
        Map<String, String> options = new HashMap<>();
        options.put("clobber", "true");
        options.put("silent", "true");
        options.put("outputpath", outputDir.getAbsolutePath());
        CfrDriver driver = new CfrDriver.Builder().withOptions(options).build();
        new Thread(() -> {
            driver.analyse(Collections.singletonList(jarFile));
        }).start();
    }
}
```

**Comment by leibnitz27** [comment]
Hah, that was fun - couldn't reproduce on my normal dev laptop, had to find a better specced machine.
