### ISSUE TITLE
StackOverflowError 

### ISSUE THREAD

**Issue by gangjian0917** [leibnitz27/cfr#257]
# CFR version

0.151

# Compiler

javac 1.8.0_291

# Description

When decompiling jars, some can run into an infinite recursion issue
Snippet of the StackOverflowError:
`Caused by: java.lang.StackOverflowError
	at org.benf.cfr.reader.bytecode.analysis.loc.BytecodeLocFactoryImpl.combine(BytecodeLocFactoryImpl.java:29)
	at org.benf.cfr.reader.bytecode.analysis.loc.BytecodeLoc.combine(BytecodeLoc.java:17)
	at org.benf.cfr.reader.bytecode.analysis.parse.statement.ForIterStatement.getCombinedLoc(ForIterStatement.java:31)
	at org.benf.cfr.reader.bytecode.analysis.loc.BytecodeLocFactoryImpl.getLocs(BytecodeLocFactoryImpl.java:61)
	at org.benf.cfr.reader.bytecode.analysis.loc.BytecodeLocFactoryImpl.combine(BytecodeLocFactoryImpl.java:33)
	at org.benf.cfr.reader.bytecode.analysis.loc.BytecodeLoc.combine(BytecodeLoc.java:17)
	at org.benf.cfr.reader.bytecode.analysis.parse.statement.ForIterStatement.getCombinedLoc(ForIterStatement.java:31)
	at org.benf.cfr.reader.bytecode.analysis.loc.BytecodeLocFactoryImpl.getLocs(BytecodeLocFactoryImpl.java:61)
        ...
	at org.benf.cfr.reader.bytecode.analysis.loc.BytecodeLocFactoryImpl.combine(BytecodeLocFactoryImpl.java:33)
	at org.benf.cfr.reader.bytecode.analysis.loc.BytecodeLoc.combine(BytecodeLoc.java:17)
	at org.benf.cfr.reader.bytecode.analysis.parse.statement.ForIterStatement.getCombinedLoc(ForIterStatement.java:31)
	at org.benf.cfr.reader.bytecode.analysis.loc.BytecodeLocFactoryImpl.getLocs(BytecodeLocFactoryImpl.java:61)`

# Example

<pre>
    public static void main(String[] args) {
        String outputDirectory = "/Users/jamesding/Downloads/output";
        CfrDriver cfrDriver = new CfrDriver.Builder().withOptions(
                new HashMap<String, String>() {{
                    put("outputdir", outputDirectory);
                }})
                .build();
        cfrDriver.analyse(Collections.singletonList("/Users/jamesding/Downloads/com.eg.android.AlipayGphone_1625032982951.jar"));
        Collection<File> list =  FileUtils.listFiles(new File(outputDirectory), new String[]{"java"}, true);
        System.out.println(list);
    }
</pre>

**Comment by gangjian0917** [comment]
this is the jar file
[https://drive.google.com/file/d/1lTE8YkFDRlh_AOv5zUXVVFgH-jMnJ6xu/view?usp=sharing](url)
