### ISSUE TITLE
java.lang.ClassCastException: org.benf.cfr.reader.entities.attributes.AttributeUnknown cannot be cast to org.benf.cfr.reader.entities.attributes.AttributeRuntimeInvisibleAnnotations

### ISSUE THREAD

**Issue by Cubxity** [leibnitz27/cfr#48]
**Stacktrace**:
```
java.lang.ClassCastException: org.benf.cfr.reader.entities.attributes.AttributeUnknown cannot be cast to org.benf.cfr.reader.entities.attributes.AttributeRuntimeInvisibleAnnotations
	at org.benf.cfr.reader.entities.classfilehelpers.AbstractClassFileDumper.dumpAnnotations(AbstractClassFileDumper.java:169)
	at org.benf.cfr.reader.entities.classfilehelpers.ClassFileDumperNormal.dump(ClassFileDumperNormal.java:66)
	at org.benf.cfr.reader.entities.ClassFile.dump(ClassFile.java:1070)
	at org.benf.cfr.reader.Driver.doClass(Driver.java:83)
	at org.benf.cfr.reader.CfrDriverImpl.analyse(CfrDriverImpl.java:67)
```

**Comment by leibnitz27** [comment]
Have you got a sample class file to reproduce this? Thanks.

**Comment by leibnitz27** [comment]
Oh that's quite fun actually.   If the invisible attribute is corrupt, java will ignore it, but CFR would substitute a placeholder.
